# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
  
- task: Bash@3
  inputs:
      targetType: 'inline'
      script: |
        curl \
          -X PUT \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $(TOKEN_VALUE)" \
          https://api.github.com/orgs/$(ORG_NAME)/teams/$(TEAM_NAME)/memberships/$(USER_ID) \
          -d '{"role":"$(PERMISSION)"}'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
