# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

  
- task: Bash@3
  inputs:
      targetType: 'inline'
      script: |
        curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $(TOKEN_ID)" \
          https://api.github.com/orgs/$(ORG_NAME)/teams \
          -d '{"name":"$(TEAM_NAME)","description":"This team is for dev team","permission":"$(ACCESS_LEVEL)","privacy":"closed"}'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
